In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [3]:
X = df.drop('Purchased',axis=1)
y = df['Purchased']

In [4]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [5]:
X_scaled = scaler.fit_transform(X.to_numpy())

In [6]:
XS = pd.DataFrame(X_scaled, columns=['Age','EstimatedSalary'])

In [7]:
XS.head()

Age  EstimatedSalary
0  0.023810         0.029630
1  0.404762         0.037037
2  0.190476         0.207407
3  0.214286         0.311111
4  0.023810         0.451852

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(XS,y, test_size=0.30, random_state=1)

In [10]:
X_train.shape

(280, 2)

In [11]:
X_test.shape

(120, 2)

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
logmodel = LogisticRegression(penalty='none')
logmodel.fit(X_train,y_train)

LogisticRegression(penalty='none')

In [14]:
predictions = logmodel.predict(X_test)

In [15]:
from sklearn.metrics import classification_report

In [16]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86        72
           1       0.81      0.73      0.77        48

    accuracy                           0.82       120
   macro avg       0.82      0.81      0.81       120
weighted avg       0.82      0.82      0.82       120



In [17]:
print(X_test[:10])
print('-'*15)
print(predictions[:10])

          Age  EstimatedSalary
398  0.428571         0.133333
125  0.500000         0.340741
328  0.428571         0.762963
339  0.500000         0.792593
172  0.190476         0.762963
342  0.476190         0.370370
197  0.047619         0.155556
291  0.738095         0.548148
29   0.309524         0.022222
284  0.714286         0.933333
---------------
[0 0 1 1 0 0 0 1 0 1]


In [18]:
print(predictions[:10])
print(y_test[:10])

[0 0 1 1 0 0 0 1 0 1]
398    0
125    0
328    1
339    1
172    0
342    0
197    0
291    1
29     0
284    0
Name: Purchased, dtype: int64


In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
print(confusion_matrix(y_test,predictions))

[[64  8]
 [13 35]]


In [21]:
import statsmodels.api as sm

In [22]:
X1 = sm.add_constant(X_train)
reg_log = sm.Logit(y_train,X1)
results_log = reg_log.fit()

Optimization terminated successfully.
         Current function value: 0.318521
         Iterations 8


In [23]:
results_log.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:              Purchased   No. Observations:                  280
Model:                          Logit   Df Residuals:                      277
Method:                           MLE   Df Model:                            2
Date:                Mon, 05 Feb 2024   Pseudo R-squ.:                  0.5027
Time:                        22:26:30   Log-Likelihood:                -89.186
converged:                       True   LL-Null:                       -179.36
Covariance Type:            nonrobust   LLR p-value:                 6.905e-40
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -8.7237      1.120     -7.792      0.000     -10.918      -6.529
Age                10.6148      1.483      7.156      0.000       7.708      13.522
EstimatedSalary     6.3341      1.038      6.102      0.000       4.300       8.369
===================================================================================
"""

In [24]:
logmodel.coef_

array([[10.61487105,  6.33414153]])

In [25]:
logmodel.intercept_

array([-8.72372405])

In [26]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [27]:
# 5 folds selected
kfold = KFold(n_splits=5, random_state=0, shuffle=True)
model = LogisticRegression(solver='liblinear')
results = cross_val_score(model, XS, y, cv=kfold)
# Output the accuracy. Calculate the mean and std across all folds.
print("Accuracy: %.3f%%" % (results.mean()*100.0))

Accuracy: 82.750%


In [28]:
results

array([0.925 , 0.7375, 0.725 , 0.8   , 0.95  ])